/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers"
import { BytesLike } from "@ethersproject/bytes"
import { Listener, Provider } from "@ethersproject/providers"
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi"
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons"

interface CoinviseABIInterface extends ethers.utils.Interface {
  functions: {
    "_initialize(string,string)": FunctionFragment
    "airdropPerLinkWeiCharged()": FunctionFragment
    "buyToken(uint256,address,uint256)": FunctionFragment
    "claim(address,uint256,bytes32,bytes32,uint8)": FunctionFragment
    "createCampaign(address,uint256,uint256)": FunctionFragment
    "depositPercentageCharged()": FunctionFragment
    "depositPercentageChargedDecimals()": FunctionFragment
    "depositToken(address,uint256,uint256)": FunctionFragment
    "executeMetaTransaction(address,bytes,bytes32,bytes32,uint8)": FunctionFragment
    "getCampaign(address,uint256)": FunctionFragment
    "getCampaignIdsFromManager(address)": FunctionFragment
    "getCampaignRewardedCount(address,uint256)": FunctionFragment
    "getCoinviseBalance()": FunctionFragment
    "getDeposit(address,uint256)": FunctionFragment
    "getDepositIdsFromOwner(address)": FunctionFragment
    "getDepositOwnerBalance()": FunctionFragment
    "getNonce(address)": FunctionFragment
    "initialize(address,uint256,uint256,uint256,uint256)": FunctionFragment
    "multisend(address,address[],uint256[])": FunctionFragment
    "multisendPerLinkWeiCharged()": FunctionFragment
    "owner()": FunctionFragment
    "renounceOwnership()": FunctionFragment
    "setAirdropPremiums(uint256)": FunctionFragment
    "setDepositPremiums(uint256,uint256)": FunctionFragment
    "setMultisendPremiums(uint256)": FunctionFragment
    "setTrustedAddress(address)": FunctionFragment
    "transferOwnership(address)": FunctionFragment
    "withdraw()": FunctionFragment
    "withdrawDeposit(uint256)": FunctionFragment
    "withdrawDepositOwnerBalance()": FunctionFragment
    "withdrawRemainingBalanceFromCampaign(uint256)": FunctionFragment
  }

  encodeFunctionData(functionFragment: "_initialize", values: [string, string]): string
  encodeFunctionData(functionFragment: "airdropPerLinkWeiCharged", values?: undefined): string
  encodeFunctionData(functionFragment: "buyToken", values: [BigNumberish, string, BigNumberish]): string
  encodeFunctionData(
    functionFragment: "claim",
    values: [string, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string
  encodeFunctionData(functionFragment: "createCampaign", values: [string, BigNumberish, BigNumberish]): string
  encodeFunctionData(functionFragment: "depositPercentageCharged", values?: undefined): string
  encodeFunctionData(functionFragment: "depositPercentageChargedDecimals", values?: undefined): string
  encodeFunctionData(functionFragment: "depositToken", values: [string, BigNumberish, BigNumberish]): string
  encodeFunctionData(
    functionFragment: "executeMetaTransaction",
    values: [string, BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string
  encodeFunctionData(functionFragment: "getCampaign", values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: "getCampaignIdsFromManager", values: [string]): string
  encodeFunctionData(functionFragment: "getCampaignRewardedCount", values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: "getCoinviseBalance", values?: undefined): string
  encodeFunctionData(functionFragment: "getDeposit", values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: "getDepositIdsFromOwner", values: [string]): string
  encodeFunctionData(functionFragment: "getDepositOwnerBalance", values?: undefined): string
  encodeFunctionData(functionFragment: "getNonce", values: [string]): string
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string
  encodeFunctionData(functionFragment: "multisend", values: [string, string[], BigNumberish[]]): string
  encodeFunctionData(functionFragment: "multisendPerLinkWeiCharged", values?: undefined): string
  encodeFunctionData(functionFragment: "owner", values?: undefined): string
  encodeFunctionData(functionFragment: "renounceOwnership", values?: undefined): string
  encodeFunctionData(functionFragment: "setAirdropPremiums", values: [BigNumberish]): string
  encodeFunctionData(functionFragment: "setDepositPremiums", values: [BigNumberish, BigNumberish]): string
  encodeFunctionData(functionFragment: "setMultisendPremiums", values: [BigNumberish]): string
  encodeFunctionData(functionFragment: "setTrustedAddress", values: [string]): string
  encodeFunctionData(functionFragment: "transferOwnership", values: [string]): string
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string
  encodeFunctionData(functionFragment: "withdrawDeposit", values: [BigNumberish]): string
  encodeFunctionData(functionFragment: "withdrawDepositOwnerBalance", values?: undefined): string
  encodeFunctionData(functionFragment: "withdrawRemainingBalanceFromCampaign", values: [BigNumberish]): string

  decodeFunctionResult(functionFragment: "_initialize", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "airdropPerLinkWeiCharged", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "buyToken", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "createCampaign", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "depositPercentageCharged", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "depositPercentageChargedDecimals", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "depositToken", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "executeMetaTransaction", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "getCampaign", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "getCampaignIdsFromManager", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "getCampaignRewardedCount", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "getCoinviseBalance", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "getDepositIdsFromOwner", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "getDepositOwnerBalance", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "multisend", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "multisendPerLinkWeiCharged", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "renounceOwnership", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "setAirdropPremiums", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "setDepositPremiums", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "setMultisendPremiums", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "setTrustedAddress", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "withdrawDeposit", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "withdrawDepositOwnerBalance", data: BytesLike): Result
  decodeFunctionResult(functionFragment: "withdrawRemainingBalanceFromCampaign", data: BytesLike): Result

  events: {
    "Bought(address,uint256,address,address,uint256,uint256)": EventFragment
    "CampaignCreated(uint256)": EventFragment
    "Deposited(uint256,address,address,uint256,uint256)": EventFragment
    "MetaTransactionExecuted(address,address,bytes)": EventFragment
    "Multisent(address,uint256,uint256)": EventFragment
    "OwnershipTransferred(address,address)": EventFragment
    "UserRewarded(address,uint256,address,address,uint256)": EventFragment
    "Withdrawn(address,uint256)": EventFragment
    "WithdrawnDepositOwnerBalance(address,uint256)": EventFragment
  }

  getEvent(nameOrSignatureOrTopic: "Bought"): EventFragment
  getEvent(nameOrSignatureOrTopic: "CampaignCreated"): EventFragment
  getEvent(nameOrSignatureOrTopic: "Deposited"): EventFragment
  getEvent(nameOrSignatureOrTopic: "MetaTransactionExecuted"): EventFragment
  getEvent(nameOrSignatureOrTopic: "Multisent"): EventFragment
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment
  getEvent(nameOrSignatureOrTopic: "UserRewarded"): EventFragment
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment
  getEvent(nameOrSignatureOrTopic: "WithdrawnDepositOwnerBalance"): EventFragment
}

export type BoughtEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber, BigNumber] & {
    user: string
    depositId: BigNumber
    owner: string
    token: string
    amount: BigNumber
    price: BigNumber
  }
>

export type CampaignCreatedEvent = TypedEvent<[BigNumber] & { campaignId: BigNumber }>

export type DepositedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber] & {
    depositId: BigNumber
    depositor: string
    token: string
    amount: BigNumber
    price: BigNumber
  }
>

export type MetaTransactionExecutedEvent = TypedEvent<
  [string, string, string] & {
    userAddress: string
    relayerAddress: string
    functionSignature: string
  }
>

export type MultisentEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    tokenAddress: string
    recipientsAmount: BigNumber
    amount: BigNumber
  }
>

export type OwnershipTransferredEvent = TypedEvent<[string, string] & { previousOwner: string; newOwner: string }>

export type UserRewardedEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber] & {
    managerAddress: string
    campaignId: BigNumber
    userAddress: string
    tokenAddress: string
    amount: BigNumber
  }
>

export type WithdrawnEvent = TypedEvent<[string, BigNumber] & { recipient: string; amount: BigNumber }>

export type WithdrawnDepositOwnerBalanceEvent = TypedEvent<[string, BigNumber] & { user: string; amount: BigNumber }>

export class CoinviseABI extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: CoinviseABIInterface

  functions: {
    _initialize(
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    airdropPerLinkWeiCharged(overrides?: CallOverrides): Promise<[BigNumber]>

    buyToken(
      _depositId: BigNumberish,
      _owner: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    claim(
      _campaignManager: string,
      _campaignId: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    createCampaign(
      _tokenAddress: string,
      _linksAmount: BigNumberish,
      _amountPerLink: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    depositPercentageCharged(overrides?: CallOverrides): Promise<[BigNumber]>

    depositPercentageChargedDecimals(overrides?: CallOverrides): Promise<[BigNumber]>

    depositToken(
      _token: string,
      _amount: BigNumberish,
      _price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    executeMetaTransaction(
      userAddress: string,
      functionSignature: BytesLike,
      sigR: BytesLike,
      sigS: BytesLike,
      sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    getCampaign(
      _campaignManager: string,
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber]>

    getCampaignIdsFromManager(_campaignManager: string, overrides?: CallOverrides): Promise<[BigNumber[]]>

    getCampaignRewardedCount(
      _manager: string,
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    getCoinviseBalance(overrides?: CallOverrides): Promise<[BigNumber]>

    getDeposit(
      _owner: string,
      _depositId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string, string, BigNumber, BigNumber, BigNumber]>

    getDepositIdsFromOwner(_owner: string, overrides?: CallOverrides): Promise<[BigNumber[]]>

    getDepositOwnerBalance(overrides?: CallOverrides): Promise<[BigNumber]>

    getNonce(user: string, overrides?: CallOverrides): Promise<[BigNumber] & { nonce: BigNumber }>

    initialize(
      _trustedAddress: string,
      _airdropPerLinkWeiCharged: BigNumberish,
      _multisendPerLinkWeiCharged: BigNumberish,
      _depositPercentageCharged: BigNumberish,
      _depositPercentageChargedDecimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    multisend(
      _token: string,
      _recipients: string[],
      _amounts: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    multisendPerLinkWeiCharged(overrides?: CallOverrides): Promise<[BigNumber]>

    owner(overrides?: CallOverrides): Promise<[string]>

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    setAirdropPremiums(
      _airdropPerLinkWeiCharged: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setDepositPremiums(
      _depositPercentageCharged: BigNumberish,
      _depositPercentageChargedDecimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setMultisendPremiums(
      _mulisendPerLinkWeiCharged: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setTrustedAddress(
      _trustedAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    withdrawDeposit(
      _depositId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    withdrawDepositOwnerBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    withdrawRemainingBalanceFromCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>
  }

  _initialize(
    _name: string,
    _version: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  airdropPerLinkWeiCharged(overrides?: CallOverrides): Promise<BigNumber>

  buyToken(
    _depositId: BigNumberish,
    _owner: string,
    _amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  claim(
    _campaignManager: string,
    _campaignId: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    v: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  createCampaign(
    _tokenAddress: string,
    _linksAmount: BigNumberish,
    _amountPerLink: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  depositPercentageCharged(overrides?: CallOverrides): Promise<BigNumber>

  depositPercentageChargedDecimals(overrides?: CallOverrides): Promise<BigNumber>

  depositToken(
    _token: string,
    _amount: BigNumberish,
    _price: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  executeMetaTransaction(
    userAddress: string,
    functionSignature: BytesLike,
    sigR: BytesLike,
    sigS: BytesLike,
    sigV: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  getCampaign(
    _campaignManager: string,
    _campaignId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber]>

  getCampaignIdsFromManager(_campaignManager: string, overrides?: CallOverrides): Promise<BigNumber[]>

  getCampaignRewardedCount(_manager: string, _campaignId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  getCoinviseBalance(overrides?: CallOverrides): Promise<BigNumber>

  getDeposit(
    _owner: string,
    _depositId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string, string, BigNumber, BigNumber, BigNumber]>

  getDepositIdsFromOwner(_owner: string, overrides?: CallOverrides): Promise<BigNumber[]>

  getDepositOwnerBalance(overrides?: CallOverrides): Promise<BigNumber>

  getNonce(user: string, overrides?: CallOverrides): Promise<BigNumber>

  initialize(
    _trustedAddress: string,
    _airdropPerLinkWeiCharged: BigNumberish,
    _multisendPerLinkWeiCharged: BigNumberish,
    _depositPercentageCharged: BigNumberish,
    _depositPercentageChargedDecimals: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  multisend(
    _token: string,
    _recipients: string[],
    _amounts: BigNumberish[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  multisendPerLinkWeiCharged(overrides?: CallOverrides): Promise<BigNumber>

  owner(overrides?: CallOverrides): Promise<string>

  renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  setAirdropPremiums(
    _airdropPerLinkWeiCharged: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  setDepositPremiums(
    _depositPercentageCharged: BigNumberish,
    _depositPercentageChargedDecimals: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  setMultisendPremiums(
    _mulisendPerLinkWeiCharged: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  setTrustedAddress(
    _trustedAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  withdrawDeposit(
    _depositId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  withdrawDepositOwnerBalance(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  withdrawRemainingBalanceFromCampaign(
    _campaignId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    _initialize(_name: string, _version: string, overrides?: CallOverrides): Promise<void>

    airdropPerLinkWeiCharged(overrides?: CallOverrides): Promise<BigNumber>

    buyToken(_depositId: BigNumberish, _owner: string, _amount: BigNumberish, overrides?: CallOverrides): Promise<void>

    claim(
      _campaignManager: string,
      _campaignId: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    createCampaign(
      _tokenAddress: string,
      _linksAmount: BigNumberish,
      _amountPerLink: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    depositPercentageCharged(overrides?: CallOverrides): Promise<BigNumber>

    depositPercentageChargedDecimals(overrides?: CallOverrides): Promise<BigNumber>

    depositToken(
      _token: string,
      _amount: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    executeMetaTransaction(
      userAddress: string,
      functionSignature: BytesLike,
      sigR: BytesLike,
      sigS: BytesLike,
      sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>

    getCampaign(
      _campaignManager: string,
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber]>

    getCampaignIdsFromManager(_campaignManager: string, overrides?: CallOverrides): Promise<BigNumber[]>

    getCampaignRewardedCount(_manager: string, _campaignId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getCoinviseBalance(overrides?: CallOverrides): Promise<BigNumber>

    getDeposit(
      _owner: string,
      _depositId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string, string, BigNumber, BigNumber, BigNumber]>

    getDepositIdsFromOwner(_owner: string, overrides?: CallOverrides): Promise<BigNumber[]>

    getDepositOwnerBalance(overrides?: CallOverrides): Promise<BigNumber>

    getNonce(user: string, overrides?: CallOverrides): Promise<BigNumber>

    initialize(
      _trustedAddress: string,
      _airdropPerLinkWeiCharged: BigNumberish,
      _multisendPerLinkWeiCharged: BigNumberish,
      _depositPercentageCharged: BigNumberish,
      _depositPercentageChargedDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    multisend(_token: string, _recipients: string[], _amounts: BigNumberish[], overrides?: CallOverrides): Promise<void>

    multisendPerLinkWeiCharged(overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<string>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    setAirdropPremiums(_airdropPerLinkWeiCharged: BigNumberish, overrides?: CallOverrides): Promise<void>

    setDepositPremiums(
      _depositPercentageCharged: BigNumberish,
      _depositPercentageChargedDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    setMultisendPremiums(_mulisendPerLinkWeiCharged: BigNumberish, overrides?: CallOverrides): Promise<void>

    setTrustedAddress(_trustedAddress: string, overrides?: CallOverrides): Promise<void>

    transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>

    withdraw(overrides?: CallOverrides): Promise<void>

    withdrawDeposit(_depositId: BigNumberish, overrides?: CallOverrides): Promise<void>

    withdrawDepositOwnerBalance(overrides?: CallOverrides): Promise<void>

    withdrawRemainingBalanceFromCampaign(_campaignId: BigNumberish, overrides?: CallOverrides): Promise<void>
  }

  filters: {
    "Bought(address,uint256,address,address,uint256,uint256)"(
      user?: null,
      depositId?: null,
      owner?: null,
      token?: null,
      amount?: null,
      price?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string, BigNumber, BigNumber],
      {
        user: string
        depositId: BigNumber
        owner: string
        token: string
        amount: BigNumber
        price: BigNumber
      }
    >

    Bought(
      user?: null,
      depositId?: null,
      owner?: null,
      token?: null,
      amount?: null,
      price?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string, BigNumber, BigNumber],
      {
        user: string
        depositId: BigNumber
        owner: string
        token: string
        amount: BigNumber
        price: BigNumber
      }
    >

    "CampaignCreated(uint256)"(
      campaignId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { campaignId: BigNumber }>

    CampaignCreated(campaignId?: BigNumberish | null): TypedEventFilter<[BigNumber], { campaignId: BigNumber }>

    "Deposited(uint256,address,address,uint256,uint256)"(
      depositId?: null,
      depositor?: string | null,
      token?: null,
      amount?: null,
      price?: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, BigNumber],
      {
        depositId: BigNumber
        depositor: string
        token: string
        amount: BigNumber
        price: BigNumber
      }
    >

    Deposited(
      depositId?: null,
      depositor?: string | null,
      token?: null,
      amount?: null,
      price?: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, BigNumber],
      {
        depositId: BigNumber
        depositor: string
        token: string
        amount: BigNumber
        price: BigNumber
      }
    >

    "MetaTransactionExecuted(address,address,bytes)"(
      userAddress?: null,
      relayerAddress?: null,
      functionSignature?: null
    ): TypedEventFilter<
      [string, string, string],
      { userAddress: string; relayerAddress: string; functionSignature: string }
    >

    MetaTransactionExecuted(
      userAddress?: null,
      relayerAddress?: null,
      functionSignature?: null
    ): TypedEventFilter<
      [string, string, string],
      { userAddress: string; relayerAddress: string; functionSignature: string }
    >

    "Multisent(address,uint256,uint256)"(
      tokenAddress?: string | null,
      recipientsAmount?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { tokenAddress: string; recipientsAmount: BigNumber; amount: BigNumber }
    >

    Multisent(
      tokenAddress?: string | null,
      recipientsAmount?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { tokenAddress: string; recipientsAmount: BigNumber; amount: BigNumber }
    >

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<[string, string], { previousOwner: string; newOwner: string }>

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<[string, string], { previousOwner: string; newOwner: string }>

    "UserRewarded(address,uint256,address,address,uint256)"(
      managerAddress?: string | null,
      campaignId?: BigNumberish | null,
      userAddress?: string | null,
      tokenAddress?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string, BigNumber],
      {
        managerAddress: string
        campaignId: BigNumber
        userAddress: string
        tokenAddress: string
        amount: BigNumber
      }
    >

    UserRewarded(
      managerAddress?: string | null,
      campaignId?: BigNumberish | null,
      userAddress?: string | null,
      tokenAddress?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string, BigNumber],
      {
        managerAddress: string
        campaignId: BigNumber
        userAddress: string
        tokenAddress: string
        amount: BigNumber
      }
    >

    "Withdrawn(address,uint256)"(
      recipient?: string | null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { recipient: string; amount: BigNumber }>

    Withdrawn(
      recipient?: string | null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { recipient: string; amount: BigNumber }>

    "WithdrawnDepositOwnerBalance(address,uint256)"(
      user?: null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { user: string; amount: BigNumber }>

    WithdrawnDepositOwnerBalance(
      user?: null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { user: string; amount: BigNumber }>
  }

  estimateGas: {
    _initialize(
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    airdropPerLinkWeiCharged(overrides?: CallOverrides): Promise<BigNumber>

    buyToken(
      _depositId: BigNumberish,
      _owner: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    claim(
      _campaignManager: string,
      _campaignId: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    createCampaign(
      _tokenAddress: string,
      _linksAmount: BigNumberish,
      _amountPerLink: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    depositPercentageCharged(overrides?: CallOverrides): Promise<BigNumber>

    depositPercentageChargedDecimals(overrides?: CallOverrides): Promise<BigNumber>

    depositToken(
      _token: string,
      _amount: BigNumberish,
      _price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    executeMetaTransaction(
      userAddress: string,
      functionSignature: BytesLike,
      sigR: BytesLike,
      sigS: BytesLike,
      sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    getCampaign(_campaignManager: string, _campaignId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getCampaignIdsFromManager(_campaignManager: string, overrides?: CallOverrides): Promise<BigNumber>

    getCampaignRewardedCount(_manager: string, _campaignId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getCoinviseBalance(overrides?: CallOverrides): Promise<BigNumber>

    getDeposit(_owner: string, _depositId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getDepositIdsFromOwner(_owner: string, overrides?: CallOverrides): Promise<BigNumber>

    getDepositOwnerBalance(overrides?: CallOverrides): Promise<BigNumber>

    getNonce(user: string, overrides?: CallOverrides): Promise<BigNumber>

    initialize(
      _trustedAddress: string,
      _airdropPerLinkWeiCharged: BigNumberish,
      _multisendPerLinkWeiCharged: BigNumberish,
      _depositPercentageCharged: BigNumberish,
      _depositPercentageChargedDecimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    multisend(
      _token: string,
      _recipients: string[],
      _amounts: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    multisendPerLinkWeiCharged(overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    setAirdropPremiums(
      _airdropPerLinkWeiCharged: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    setDepositPremiums(
      _depositPercentageCharged: BigNumberish,
      _depositPercentageChargedDecimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    setMultisendPremiums(
      _mulisendPerLinkWeiCharged: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    setTrustedAddress(
      _trustedAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    withdrawDeposit(
      _depositId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    withdrawDepositOwnerBalance(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    withdrawRemainingBalanceFromCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    _initialize(
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    airdropPerLinkWeiCharged(overrides?: CallOverrides): Promise<PopulatedTransaction>

    buyToken(
      _depositId: BigNumberish,
      _owner: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    claim(
      _campaignManager: string,
      _campaignId: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    createCampaign(
      _tokenAddress: string,
      _linksAmount: BigNumberish,
      _amountPerLink: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    depositPercentageCharged(overrides?: CallOverrides): Promise<PopulatedTransaction>

    depositPercentageChargedDecimals(overrides?: CallOverrides): Promise<PopulatedTransaction>

    depositToken(
      _token: string,
      _amount: BigNumberish,
      _price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    executeMetaTransaction(
      userAddress: string,
      functionSignature: BytesLike,
      sigR: BytesLike,
      sigS: BytesLike,
      sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    getCampaign(
      _campaignManager: string,
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getCampaignIdsFromManager(_campaignManager: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getCampaignRewardedCount(
      _manager: string,
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getCoinviseBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getDeposit(_owner: string, _depositId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getDepositIdsFromOwner(_owner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getDepositOwnerBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getNonce(user: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    initialize(
      _trustedAddress: string,
      _airdropPerLinkWeiCharged: BigNumberish,
      _multisendPerLinkWeiCharged: BigNumberish,
      _depositPercentageCharged: BigNumberish,
      _depositPercentageChargedDecimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    multisend(
      _token: string,
      _recipients: string[],
      _amounts: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    multisendPerLinkWeiCharged(overrides?: CallOverrides): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    setAirdropPremiums(
      _airdropPerLinkWeiCharged: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setDepositPremiums(
      _depositPercentageCharged: BigNumberish,
      _depositPercentageChargedDecimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setMultisendPremiums(
      _mulisendPerLinkWeiCharged: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setTrustedAddress(
      _trustedAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    withdrawDeposit(
      _depositId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    withdrawDepositOwnerBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    withdrawRemainingBalanceFromCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>
  }
}
